Better error reporting

diff --git a/types3-calc b/types3-calc
--- a/types3-calc
+++ b/types3-calc
@@ -3,6 +3,12 @@
 set -e
 
 WHERE=$(readlink -f "$0")
-BASEDIR=$(dirname "$WHERE")
+TYPES3_BASEDIR=$(dirname "$WHERE")
 
-exec $BASEDIR/target/release/types3 "$@"
+if [ ! -e "$TYPES3_BASEDIR/target/release/types3" ]; then
+    echo "Cannot find types-calc binary"
+    echo "Try to run util/setup.sh first!"
+    exit 1
+fi
+
+exec $TYPES3_BASEDIR/target/release/types3 "$@"
diff --git a/types3-plot b/types3-plot
--- a/types3-plot
+++ b/types3-plot
@@ -3,7 +3,13 @@
 set -e
 
 WHERE=$(readlink -f "$0")
-BASEDIR=$(dirname "$WHERE")
+TYPES3_BASEDIR=$(dirname "$WHERE")
+
+if [ ! -e "$TYPES3_BASEDIR/venv/bin/activate" ]; then
+    echo "Cannot find Python virtual environment"
+    echo "Try to run util/setup.sh first!"
+    exit 1
+fi
 
 source "$BASEDIR/venv/bin/activate"
 exec python3 $BASEDIR/python/types3-plot.py "$@"
diff --git a/types3-ui b/types3-ui
--- a/types3-ui
+++ b/types3-ui
@@ -5,5 +5,17 @@ set -e
 WHERE=$(readlink -f "$0")
 export TYPES3_BASEDIR=$(dirname "$WHERE")
 
+if [ ! -e "$TYPES3_BASEDIR/venv/bin/activate" ]; then
+    echo "Cannot find Python virtual environment"
+    echo "Try to run util/setup.sh first!"
+    exit 1
+fi
+
+if [ ! -e "$TYPES3_BASEDIR/target/release/types3" ]; then
+    echo "Cannot find types-calc binary"
+    echo "Try to run util/setup.sh first!"
+    exit 1
+fi
+
 source "$TYPES3_BASEDIR/venv/bin/activate"
 exec python3 $TYPES3_BASEDIR/python/types3-ui.py "$@"
